apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "divvun-worker-speller.fullname" . }}-data
  labels:
    {{- include "divvun-worker-speller.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  {{- if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass }}
  {{- end }}
  {{- if .Values.persistence.volumeName }}
  volumeName: {{ .Values.persistence.volumeName }}
  {{- end }}